version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - backend

  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "4000:8000"
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
